// globalVals.h
// globalVals declarations
// wpfernandes 2015-10-20 17h00min

#ifndef GLOBALVALS_H
#define GLOBALVALS_H

#include <string>
#include <vector>
#include <map>

// declarations and definitions
typedef std::vector<std::vector<double>>::size_type vsz_t; 
enum rvEnum
{ SUCCESS, NORMAL, NONE, UNKNOWN,
  CTRL_YES,
  CTRL_NO,
  CTRL_CONTINUE,
  CTRL_STOP,
  CTRL_ABORT,
  CTRL_THERE_IS_NO_ANOTHER_REGION,
  CTRL_REGION_IS_EMPTY,
  DBG,
  WRN,
  WRN_UNABLE_TO_OPEN_FILE,
  WRN_UNABLE_TO_OPEN_IN_FILE,
  WRN_UNABLE_TO_OPEN_OUT_FILE,
  WRN_FILE_ALREADY_EXISTS,
  WRN_IFSTREAM_FAILED,
  WRN_READ_FAILED,
  WRN_ENERGY_BELLOW_LIMIT,
  ERR,
  ERR_UNKNOWN_OPTION,
  ERR_OPTION_VALUE_NOT_FOUND,
  ERR_UNEXPECTED_OPTION_VALUE,
  ERR_UNEXPECTED_RETURN_OF_FUNCTION,
  ERR_FILE_NOT_FOUND,
  ERR_FILE_ALREADY_EXISTS,
  ERR_UNABLE_TO_OPEN_FILE,
  ERR_UNABLE_TO_OPEN_IN_FILE,
  ERR_UNABLE_TO_OPEN_OUT_FILE,
  ERR_UNABLE_TO_READ_EVEN_THE_FIRST_LINE,
  ERR_UNEXPECTED_EOF,
  ERR_FILE_WITH_NO_REGIONS,
  ERR_UNABLE_TO_READ_FILE,
  ERR_UNABLE_TO_READ_FILE_HEADER,
  ERR_UNABLE_TO_READ_FILE_REGIONS,
  ERR_UNABLE_TO_READ_FILE_REGION_COUNT,
  ERR_UNABLE_TO_OPEN_DEV_NULL,
  ERR_DIRECTORY_NOT_FOUND,
  ERR_NOT_A_DIRECTORY,
  ERR_ARGUMENT_NOT_FOUND,
  ERR_ARGUMENT_ISNT_DIRECTORY_OR_FILE,
  ERR_POCO_PARSE_STRING_FAILED,
  ERR_IFSTREAM_NOT_READY,
  ERR_IFSTREAM_FAILED,
  ERR_READ_COUNTS_FAILED,
  ERR_UNEXPECTED_VALUE_OF_CONTROL_VARIABLE,
  ERR_FILE_WRITING,
  ERR_UNABLE_TO_OPEN_OUTPUT_DATA_FILE,
  ERR_UNABLE_TO_OPEN_OUTPUT_SCRIPT_FILE,
  ERR_THETA_EXTRACTING_FAILED,
  ERR_PHI_EXTRACTING_FAILED,
//    err_oap_vvMUSTEXIST,// error option argument parser value validation must exist
//    err_oap_vvMUSTNOTEXIST,
//    err_oap_fvMUSTEXIST,
//    err_oap_fvMUSTNOTEXIST,
//    err_oap_dvMUSTEXIST,
//    err_oap_UNKNOWNOPTION,
//    err_PLOT2DXYSIZESDIFFER,
//    err_LOGOPENFILE_fail,
    ERR_UNKNOWN
};

//enum eEnum {eNONE, eUNKNOWN, ePDF}; // extension
//extern const std::string log_file_name_prefix;
#endif

